### ISSUE TITLE
Support for Whizbang Decks

### ISSUE THREAD

**Issue by Caedis** [MGK82/PackTracker#18]
Whizbang the Wonderful automatically chooses 1 of the 18 (2 per class) deck recipe decks and uses that as your deck.
In the collection page, it will show your deck as 1/1 when Whizbang is added.

The decks: https://www.hearthstonetopdecks.com/guides/whizbang-the-wonderful-deck-recipes-list-hero-power-golden-decks-more/

**Comment by MGK82** [comment]
What does that have to do with Pack Tracker?

**Comment by Caedis** [comment]
Oh, wow I derped. Meant to put this in the main HDT repo
