### ISSUE TITLE
How to add manually a pack ?

### ISSUE THREAD

**Issue by Siphyroth** [MGK82/PackTracker#19]
Hello !

First of all, great works about that plugins. I really appreciate it for months now.

Last night, I missed to open my HDT and for the first time I opened a pack without tracking it. I was really disappointed.

In order to try to add it manually, I took a look at the database and I could understand and spotted most of the lines and their meanings. Only area of ​​shadows that persists, the opening time which is a long code and the number of each card to enter the ones I got.

Can any one help me for the first one mostly. The time was 23H00 from the 10-09-2018.

Thanks ^^

**Comment by MGK82** [comment]
https://www.venea.net/web/net_ticks_datetime_converter#date_time_to_net_ticks_conversion
Use "Date Time to Ticks". Note the time zone of GMT / UTC.

See also: https://github.com/MGK82/PackTracker/issues/5#issuecomment-321922921

**Comment by MGK82** [comment]
You're welcome.
