### ISSUE TITLE
plz update for  Knights of the Frozen Throne

### ISSUE THREAD

**Issue by sdbds** [MGK82/PackTracker#2]
cant wait to open new packs.

**Comment by MGK82** [comment]
The update was prepared a month ago. I just needed to know the new pack-id for completion.
It comes now plus a little new extra feature while pack opening.

But don't worry. It is designed that it will store all packs you open, even tho the pack series is unknown to it. It will show the id and with a new version it shows the packnames, just as usual.
Opening Knights of the Frozen Throne or any later expansion with any version shouldn't be a problem.
