### ISSUE TITLE
Classic Duplicated Pack

### ISSUE THREAD

**Issue by gony06** [MGK82/PackTracker#3]
Good morning, first of all, apologize for my English.
I contact you to inform that after updating to the latest version, when opening a classic pack, the plug-in pack tracker has counted it 2 times, and I would like to know how to solve it.
Thank you very much.

**Comment by sdbds** [comment]
me too.
i think that turn on spoil and Pity Timer Overlay at the same time.
when i close Pity Timer Overlay,it worked.

**Comment by gony06** [comment]
Ok, I "fix" it.
I edited the file History.xml located in AppData\Roaming\HearthstoneDeckTracker\PackTracker

**Comment by MGK82** [comment]
Hmm... that should not be possible to happen. I opened my classic pack from tavern brawl last night and had no issues. The overlays are pure UI and don't have anything to do with the store mechanism, nor with the history stored to your ram. Actually, the history object in memory tells the overlays to appear/update, not the other way around.

I gonna have a look into it. I have an idea how that could happen.

For now, @gony06 is right. The history is stored on your hd. Click on plugin folder in HDT, go one folder up, then PackTracker/ There is the history.xml and the settings.xml. It's plain simple xml, you can remove packs with a simple text editor. Just make sure to not produce sysntax errors in the xml. The plugin will load an empty history to memory in that case. If you open a pack then, it will override your existing history.xml. with the empty history. Make a backup before you edit it.

**Comment by gony06** [comment]
Thank you very much :)

**Comment by MGK82** [comment]
Ok, I had it tested and it was actually possible to have packs stored multiple times.
To reproduce it, you need to turn the pack tracker off and on again. For every time it was turned on, it would store a pack one more time. I hope that covers your cases. A fix is already live and should come to you through the auto update or can be download, just as usual.

Hf and please report more, share your ideas or tell me that I make a great job. ;)

PS. I keep this open for another day in case there is more to discuss.
