### ISSUE TITLE
Will this plugin be updated for incoming scholomancer academy?

### ISSUE THREAD

**Issue by omgfrost** [MGK82/PackTracker#33]
Hello,
like title says, if it's possible before or on 6th of August the xpac release day.
If not, i guess it will just show a number like the old expansions when it wasn't updated for them yet?
thanks in advance

**Comment by Lonsol** [comment]
New expansion is out, but it hasn't been updated. Isn't tracking the new packs. :(

**Comment by omgfrost** [comment]
> New expansion is out, but it hasn't been updated. Isn't tracking the new packs. :(

yes it's kinda working. New expac packs are this number: 
![24Q8WfA 1](https://user-images.githubusercontent.com/14861120/89568814-263a5200-d824-11ea-91be-fc766ac19413.png)

**Comment by Lonsol** [comment]
> > New expansion is out, but it hasn't been updated. Isn't tracking the new packs. :(
> 
> yes it's kinda working. New expac packs are this number:
> ![24Q8WfA 1](https://user-images.githubusercontent.com/14861120/89568814-263a5200-d824-11ea-91be-fc766ac19413.png)

That's weird. When I opened a couple Scholomance packs, they weren't even logged.

**Comment by omgfrost** [comment]
Why reopened? I just update it and the spoil function is cool too. It's working like a charm for me!Thanks

**Comment by MGK82** [comment]
Update is out

> That's weird. When I opened a couple Scholomance packs, they weren't even logged.
It always tracks. Replacing the id with a propper name is a UI thing and has nothing to do with its business logic.

> Why reopened? I just update it and the spoil function is cool too. It's working like a charm for me!Thanks
Felt the need for a reply.
