### ISSUE TITLE
Update for Darkmoon Faire incoming?

### ISSUE THREAD

**Issue by x-ProgrammEd-x** [MGK82/PackTracker#36]
Hi there,

great job on the plugin. Was wondering whether it is still maintained and whether a Darkmoon Faire Update is planned. Was planning to wait with opening packs until it's available.

Cheers

**Comment by omgfrost** [comment]
me too! +1

**Comment by Ellekappae** [comment]
Hi, you should be able to track your opened packs even if the plugin is not updated.
You just don't see the expansion name but a number instead. Read the other comments around if still in doubt.

**Comment by omgfrost** [comment]
> Hi, you should be able to track your opened packs even if the plugin is not updated.
> You just don't see the expansion name but a number instead. Read the other comments around if still in doubt.

Yeah i saw it's number is 
![JRhj8UX 1](https://user-images.githubusercontent.com/14861120/99638841-2400aa00-2a47-11eb-84c4-91394395076c.png)
Any ETA on when it will be properly renamed?
Thanks in advance

**Comment by omgfrost** [comment]
> > Hi, you should be able to track your opened packs even if the plugin is not updated.
> > You just don't see the expansion name but a number instead. Read the other comments around if still in doubt.
> 
> Yeah i saw it's number is
> ![JRhj8UX 1](https://user-images.githubusercontent.com/14861120/99638841-2400aa00-2a47-11eb-84c4-91394395076c.png)
> Any ETA on when it will be properly renamed?
> Thanks in advance

BUMP

**Comment by x-ProgrammEd-x** [comment]
Says "470" for me. I think that's the ID mentioned in other posts, too.
![grafik](https://user-images.githubusercontent.com/14836146/99909991-f12b1000-2ceb-11eb-8853-3d3a2f22c8e6.png)

Also: BUMP

**Comment by omgfrost** [comment]
Bump Please!

**Comment by omgfrost** [comment]
Bump! (sorry but...again! :D )

**Comment by x-ProgrammEd-x** [comment]
Bump - seems discontinued...

**Comment by x-ProgrammEd-x** [comment]
Was updated, thank you
