### ISSUE TITLE
Update for Forged in the Barrens incoming?

### ISSUE THREAD

**Issue by omgfrost** [MGK82/PackTracker#40]
Hello,
as we did it previously -> [darkmoon faire](https://github.com/MGK82/PackTracker/issues/36)
any ETA for FITB?
Thanks in advance

**Comment by omgfrost** [comment]
UPDATE:
Just because i have this now (picture) and it's like NotLikeThis !
![an3OdFh 1](https://user-images.githubusercontent.com/14861120/113469638-73bc9c80-944f-11eb-8544-adea09d462fe.png)

**Comment by TheMrKochan** [comment]
Hi, check  my profile, may be find some helpful

**Comment by omgfrost** [comment]
> Hi, check my profile, may be find some helpful

Oh very nice!
But if it's you in charge now they should change gihub link in plugins page,i suppose.
Keep up the good work!

**Comment by omgfrost** [comment]
Perfect!
Thank you!
![hbqlYmx 1](https://user-images.githubusercontent.com/14861120/113477342-70da9f80-9481-11eb-8197-c439b38087cf.png)

**Comment by omgfrost** [comment]
Can, this update, be linked to your repository now?
![eDEZ47P 1](https://user-images.githubusercontent.com/14861120/113477386-b5fed180-9481-11eb-9094-171eb61cdbc8.png)

**Comment by TheMrKochan** [comment]
> Perfect!
> Thank you!

Tell me what version of HDT you have?

**Comment by TheMrKochan** [comment]
> Can, this update, be linked to your repository now?

Not yet, maybe I'll fix it soon. So far, I have encountered a problem when opening packages. The pack timer is not updated, it gives an error. (Only on version 1.14.4)

**Comment by omgfrost** [comment]
> > Perfect!
> > Thank you!
> 
> Tell me what version of HDT you have?

![WR7bvlg 1](https://user-images.githubusercontent.com/14861120/113477427-ee061480-9481-11eb-8f20-641cd57f2727.png)

**Comment by omgfrost** [comment]
> > Can, this update, be linked to your repository now?
> 
> Not yet, maybe I'll fix it soon. So far, I have encountered a problem when opening packages. The pack timer is not updated, it gives an error. (Only on version 1.14.4)

OOF! I've just sent you that version in pic above....now what?

**Comment by TheMrKochan** [comment]
> > > Can, this update, be linked to your repository now?
> > 
> > 
> > Not yet, maybe I'll fix it soon. So far, I have encountered a problem when opening packages. The pack timer is not updated, it gives an error. (Only on version 1.14.4)
> 
> OOF! I've just sent you that version in pic above....now what?

check if you will experience the same error. I want to make sure I'm the only one who's so unlucky

**Comment by omgfrost** [comment]
> > > > Can, this update, be linked to your repository now?
> > > 
> > > 
> > > Not yet, maybe I'll fix it soon. So far, I have encountered a problem when opening packages. The pack timer is not updated, it gives an error. (Only on version 1.14.4)
> > 
> > 
> > OOF! I've just sent you that version in pic above....now what?
> 
> check if you will experience the same error. I want to make sure I'm the only one who's so unlucky

got 80 gold now...asap i reach 100g i'll test it with FITB pack and let you know!

**Comment by omgfrost** [comment]
i opened a Year of the phoenix cards pack and i got this... T_T
![BOGtU7p 1](https://user-images.githubusercontent.com/14861120/113478882-efd4d580-948b-11eb-94f3-770dd1c5842b.jpg)

**Comment by omgfrost** [comment]
I need an updated asap for my hdt version as i need to keep track of packs to make the best buy

**Comment by omgfrost** [comment]
now i saw this:
![kem4dKE 1](https://user-images.githubusercontent.com/14861120/113478935-39bdbb80-948c-11eb-893e-ff30f54d1cc9.png)
`Make sure you are using the latest version of the Plugin and HDT.

System.MissingMethodException: Method not found: 'Boolean HearthMirror.Objects.Card.get_Premium()'.
   at PackTracker.PackWatcher.NewPack(Object sender, PackEventArgs e)
   at HearthWatcher.PackOpeningWatcher.PackEventHandler.Invoke(Object sender, PackEventArgs args)
   at HearthWatcher.PackOpeningWatcher.<CheckForPacks>d__13.MoveNext() in D:\a\Hearthstone-Deck-Tracker\Hearthstone-Deck-Tracker\HearthWatcher\PackOpeningWatcher.cs:line 58
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.<>c.<ThrowAsync>b__6_0(Object state)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)`

**Comment by omgfrost** [comment]
omg..how can i make this thing go away from my screen?
![RAfIcpN 1](https://user-images.githubusercontent.com/14861120/113478999-9a4cf880-948c-11eb-85e1-625a17f823df.png)

**Comment by TheMrKochan** [comment]
> omg..how can i make this thing go away from my screen?
> ![RAfIcpN 1](https://user-images.githubusercontent.com/14861120/113478999-9a4cf880-948c-11eb-85e1-625a17f823df.png)

Unfortunately, only close HDT... Or install 1.14.3 version and disable auto update... I do not know much about programming, just the base, I will try to get to the developer of the plugin.

**Comment by omgfrost** [comment]
> > omg..how can i make this thing go away from my screen?
> > ![RAfIcpN 1](https://user-images.githubusercontent.com/14861120/113478999-9a4cf880-948c-11eb-85e1-625a17f823df.png)
> 
> Unfortunately, only close HDT... Or install 1.14.3 version and disable auto update... I do not know much about programming, just the base, I will try to get to the developer of the plugin.

thanks please make it happen asap!

**Comment by TheMrKochan** [comment]
@MGK82 hello! we are all very much waiting for the plugin update for the current version, I hope it will be in the near future. also, look in the pull request for my suggestion to update the "PackNameConverter.cs" file. There are a lot of fixes out there

**Comment by TheMrKochan** [comment]
while I tried to update the plugin myself (I have 0 knowledge in programming :D) I spent 1500 gold and still could not fix the bug. I really hope for your help (do not throw us, please!)

**Comment by MGK82** [comment]
New HDT's API update is out for a couple of hours by now. Just get the official version of pack tracker or merge the changes in your custom forks.

Note that HTD will pick the youngest plugin file wise. It does not care about the version. Pack trackers auto update feature adresses that by setting the file's date to moment it was updated.

The official latest version is 1.4.0.

**Comment by TheMrKochan** [comment]
> New HDT's API update is out for a couple of hours by now. Just get the official version of pack tracker or merge the changes in your custom forks.
> 
> Note that HTD will pick the youngest plugin file wise. It does not care about the version. Pack trackers auto update feature adresses that by setting the file's date to moment it was updated.
> 
> The official latest version is 1.4.0.

when approximately will an update for the plugin be released that will support the current version of the api?

**Comment by MGK82** [comment]
1.4.0 is. If there is still something not working, let me know.

**Comment by omgfrost** [comment]
@MGK82 according to this [issue](https://github.com/MGK82/PackTracker/issues/43)
i'm the guy who installed @TheMrKochan "Forged in the Barrens" Packtracker.dll and now i got all of those numbers as you can see in that issue.
I uninstalled and reinstalled HDT but still the same, then i found History.xml and i deduced FITB is the id=533:
![D42Bm19 1](https://user-images.githubusercontent.com/14861120/113506402-fc693480-9544-11eb-9cbf-688d540fc0e5.png)
i tried to rename it and then plugin showed nothing so i put 533 back and i supposed those id are connected to the API
So how to remove all these number but maintain the history so far?

**Comment by TheMrKochan** [comment]
> 1.4.0 is. If there is still something not working, let me know.

https://github.com/MGK82/PackTracker/pull/39 please, update PackNameConvert.cs from this pull
