### ISSUE TITLE
Name of the card sets

### ISSUE THREAD

**Issue by cblp0pe3ka** [MGK82/PackTracker#47]
The names of the card sets are not displayed, instead three digits in the name are displayed.
![Screenshot_1](https://user-images.githubusercontent.com/87282347/125209954-4df03080-e2a5-11eb-8d17-e6bd64fc05cf.png)

**Comment by TheMrKochan** [comment]
Привет, смотри на это расширение: https://github.com/sgkoishi/PackTracker
Регулярно обновляют, плюс новые фичи бывают)

**Comment by cblp0pe3ka** [comment]
> Привет, смотри на это расширение: https://github.com/sgkoishi/PackTracker
> Регулярно обновляют, плюс новые фичи бывают)

Привет. Что-то не пойму, зачем создавать ещё один плагин? И будет ли он работать с моей историей открытых комплектов карт?

**Comment by TheMrKochan** [comment]
\AppData\Roaming\HearthstoneDeckTracker\PackTracker
Отсюда скопируй свои данные открытия паков и просто при переустановке плагина скопируй туда эти файлы

**Comment by cblp0pe3ka** [comment]
> \ AppData \ Roaming \ HearthstoneDeckTracker \ PackTracker
> Отсюда скопируй свои данные открытия паков и просто при переустановке плагина скопируй туда эти файлы

Спасибо за помощь, теперь названия комплектов карт отображаются правильно. Достаточно переустановить плагин, история открытых комплектов карт подтянулась автоматически.
![Screenshot_2](https://user-images.githubusercontent.com/87282347/125312098-a6264180-e33c-11eb-94c9-09820a384f45.png)
