### ISSUE TITLE
Any way to put in past history?

### ISSUE THREAD

**Issue by erikk00** [MGK82/PackTracker#5]
Didn't have this wonderful plugin before (and have opened packs on mobile before realizing I shouldn't be) and was wondering if there was any way to go back and update the stats?  I have screenshots of all my pack openings since I started thinking of it.  

Thanks.

**Comment by MGK82** [comment]
There is nothing that I have implemented and atm I don't plan anything like it. The idea of this plug in was to NOT hassle around with manual entries like all the other services.
BUT if you realy realy want to do that, you could edit the history file manually.

It is a simple xml file at %appdata%\HearthstoneDeckTracker\PackTracker\History.xml and when you copy the pattern, you can add entries. You need to know the pack id's which you can find in the [PackNameConverter.cs](https://github.com/MGK82/PackTracker/blob/391af9e15f9cc9bac43b90fc4603933a2f282742/PackHistorian/View/PackNameConverter.cs) in this project. And you need to know the card id's which you can find at [Hearthstone API](http://hearthstoneapi.com/cards). Last but not least the date and time is stored as ticks. There seems to be an [online-converter](https://www.venea.net/web/net_ticks_converter), I havn't tested it.

I highly highly highly recommend that you backup your history.xml first.

PS. I hope it's not too much of a disappointment for you and that you can still enjoy the PackTracker nevertheless. I would still like to hear from you, when you have any other suggestions or ideas.

So long and have fun.

**Comment by erikk00** [comment]
Editing an xml is exactly what I was looking for. Well, good enough I mean. :-)  

I'm never again opening a pack without HDT and this plug in but for my own stupidity in not looking into this before,  I am perfectly willing to go through the slough of putting it in manually.
