### ISSUE TITLE
Settings screen broken on dark theme

### ISSUE THREAD

**Issue by flatluigi** [MGK82/PackTracker#6]
Simple problem, simple fix -- on the dark theme, the font gets changed to white on a grey background, but the settings pane for the plugin always has a white background, leading to this on dark themes:

![issue](https://puu.sh/xlG02/e4a1cabcb3.png)

Either force the font to always be a certain color, or make the background change along with the program's overall theme.

**Comment by MGK82** [comment]
Thank you for that. It's almost night time here. Gonna have a look tomorrow after work.

**Comment by MGK82** [comment]
Fixed. Comes with the next release.
