### ISSUE TITLE
Integration with pitytracker?

### ISSUE THREAD

**Issue by Ansem93** [MGK82/PackTracker#8]
any hope to see it working with pity tracker?

**Comment by MGK82** [comment]
Hi there.

The idea of Pack Tracker is to have a full history, not just your pity counters. I don't know if it is still like that, but last time I checked, you could enter your pack content's rarity only, to Pity Tracker. Therefor, importing data of Pity Tracker is unlikely to be implemented into Pack Tracker.

On the other hand, as far as I know, the guys of HearthSim are working on online pack statistics etc. themself and an upload via DeckTracker is already in existence. But for propper information on that topic, i please you to contact them yourself. They are very friendly guys. [Discord](https://discordapp.com/invite/hearthsim) worked always good for that matter.

If you have other question or suggestion, just conact me.
So long, have a nice day. ;)
